In [ ]:
import pandas as pd


df = pd.read_csv("sales.csv")

In [4]:
df

    transaction_id    product   category quantity price
0                1       Coke     Drinks        5    15
1                2      Bread       Food        3    20
2                3       Coke     Drinks        2    15
3                4       Milk      Dairy        4    18
4                5      Bread       Food        1    20
5                6       Eggs      Dairy        2    35
6                7       Coke     Drinks        3    15
7                8       Coke     Drinks       -2    15
8                9       Milk      Dairy        5   -18
9               10      Bread       Food        0    20
10              11  Chocolate     Snacks        2    25
11              11  Chocolate     Snacks        2    25
12              12        NaN     Drinks        3    15
13              13      Juice        NaN        4    12
14              14      Water     Drinks     1000    10
15              15      Chips     Snacks      abc    20
16              16     Yogurt      Dairy        5   xyz
17              17       Soap  Household        2    30
18              18       Coke     Drinks        3    15
19              19      Bread       Food        2    20
20              20       Milk      Dairy        4    18
21              21       Milk      Dairy        4    18
22              22       Coke     Drinks   999999    15
23              23       Eggs      Dairy        1    35
24              24      Juice     Drinks        2    12
25              25  Chocolate     Snacks        3    25

    transaction_id    product category quantity price
21              21       Milk    Dairy        4    18
22              22       Coke   Drinks   999999    15
23              23       Eggs    Dairy        1    35
24              24      Juice   Drinks        2    12
25              25  Chocolate   Snacks        3    25